title: 'KI-Wiki'
description: 'Wiki zum Einsatz Künstlicher Intelligenz in Bildungsprozessen'
remote_theme: just-the-docs/just-the-docs

# Navigation Sidebar
just-the-docs:
    collections:
        pages: 
            name: Wiki
            nav_exclude: false
            search_exclude: false
    toc:
        enabled: true            # enable on-page navigation
        heading_level: 1        # starting heading level
        max_heading_level: 6    # ending heading level            
    
# enable sidebar navigation
markdown: kramdown
kramdown:
    toc_levels: 1..6
    
plugins:
  - jekyll-remote-theme

# Navigation & Struktur
nav_sort: case_sensitive    

